# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: StoneAge Waterblast Tools
email: margaret.babiarz@stoneagetools.com
description:  # this means to ignore newlines until "baseurl:"
  Manufacturing high quality waterblast tools and automated equipment for high pressure hydroblasting/industrial cleaning, sewer jetting nozzles, and downhole tools for well intervention.
baseurl: "" #  the subpath of your site, e.g. /blog
url: "http://stoneagetools.com" # the base hostname & protocol for your site
#twitter_username: ghostweasel
#github_username:  mbabiarz

# Build settings
markdown: kramdown
