# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: StoneAge Waterblast Tools – WATERBLAST EQUIPMENT FOR INDUSTRIAL CLEANING
email: margaret.babiarz@stoneagetools.com
description:  # this means to ignore newlines until "baseurl:"
  StoneAge, Inc. manufactures high-pressure waterblast tools and automated equipment for industrial cleaning applications. Our products have been an industry standard for over 40 years and we continue to lead the way with tools that advance productivity and hands-free automated equipment that ensures you complete your waterblasting jobs safely, easily, on time, and on budget.
image: /assets/img/og/propositioner-og.jpg
# baseurl: "" #  the subpath of your site, e.g. /blog
url: "https://www.stoneagetools.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: [.htaccess]